language: php

sudo: false

cache:
  directories:
    - ./travisci/tmp
    - $HOME/.composer/cache

php:
  - "7.0"
  - "5.6"
  - "5.5"
  
jdk:
  - oraclejdk7
  
before_script:
  - phpenv config-rm xdebug.ini; true
  - ./travisci/bin/ci/setup.sh
  - composer install
  
after_script:
  - ./travisci/bin/ci/stop.sh
  
